### ISSUE TITLE
pymc installation

### ISSUE THREAD

**Issue by ChayaSt** [choderalab/torsionfit#16] opened 2015-11-03 15:31 UTC
When pymc 2.3.4 is installed with ```setup.py```
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-5f262cfcb99b> in <module>()
----> 1 import pymc

/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/__init__.pyc in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: dlopen(/Users/sternc1/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/flib.so, 2): Library not loaded: /usr/local/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran.3.dylib
  Referenced from: /Users/sternc1/anaconda/lib/python2.7/site-packages/pymc-2.3.4-py2.7-macosx-10.9-x86_64.egg/pymc/flib.so
  Reason: image not found
````

When pymc is installed with conda ```conda install pymc=2.3.4``` everything works.
This seems to be a pymc issue thought.

**Comment by jchodera** [comment] 2015-11-03 15:37
This is more likely an issue with which gfortran you installed locally.  You need the fortran libraries on your dynamic library path, I believe.  You may also have to configure the fortran compiler environment in Python.

**Comment by jchodera** [comment] 2015-11-03 15:38
Can you find the conda recipe that was used to build the pymc that works?

**Comment by jchodera** [comment] 2015-11-03 15:39
Also, I wonder if we don't even need to compile pymc from source to build a library backend plugin.

**Comment by jchodera** [comment] 2015-11-03 17:11
Conda recipe is here:
https://github.com/pymc-devs/pymc/tree/master/conda

Looks like [`build.sh`](https://github.com/pymc-devs/pymc/blob/master/conda/build.sh) copies the `libgfortran` files after building:
```bash
#!/bin/bash
if [ "$(uname)" == "Darwin" ]; then
    # export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch x86_64"
    cp /usr/local/Cellar/gcc/4.9.1/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgfortran*.*a .
    LDFLAGS="-undefined dynamic_lookup -bundle -Wl,-search_paths_first -L$(pwd) $LDFLAGS"
fi

$PYTHON setup.py build
$PYTHON setup.py install
```

**Comment by ChayaSt** [comment] 2015-12-18 19:04
@jchodera, you mentioned that installing one of the dependencies via conda of ```torsionfit``` broke ```pymc```.  Do you still get that? and is it related to this issue?

**Comment by jchodera** [comment] 2015-12-20 00:25
OK, I am super confused.  On the cbio cluster, just installing `pymc` on its own doesn't work:
```
[chodera@mskcc-ln1 ~]$ bash Miniconda-latest-Linux-x86_64.sh -b -p miniconda
...
[chodera@mskcc-ln1 ~]$ conda install --yes pymc
Fetching package metadata: ........
Solving package specifications: .....................
Package plan for installation in environment /cbio/jclab/home/chodera/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-1.0            |                0         170 KB
    openblas-0.2.14            |                3         3.5 MB
    numpy-1.10.2               |           py27_0         5.9 MB
    setuptools-19.1.1          |           py27_0         345 KB
    scipy-0.16.1               |      np110py27_0        23.9 MB
    pymc-2.3.6                 |      np110py27_0         637 KB
    ------------------------------------------------------------
                                           Total:        34.4 MB

The following NEW packages will be INSTALLED:

    libgfortran: 1.0-0             
    numpy:       1.10.2-py27_0     
    openblas:    0.2.14-3          
    pymc:        2.3.6-np110py27_0 
    scipy:       0.16.1-np110py27_0

The following packages will be UPDATED:

    setuptools:  18.8.1-py27_0 --> 19.1.1-py27_0     

Fetching packages ...
...
[chodera@mskcc-ln1 ~]$ python
Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pymc
Fatal Python error: Couldn't create autoTLSkey mapping
Abort
[chodera@mskcc-ln1 ~]$ 
```

**Comment by jchodera** [comment] 2015-12-20 00:26
OK, well it *does* work on the nodes.
```
[chodera@mskcc-ln1 ~]$ interactive
qsub: waiting for job 6671075.mskcc-fe1.local to start
qsub: job 6671075.mskcc-fe1.local ready
[chodera@gpu-2-17 ~]$ python
imPython 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pymc
>>> 
```

**Comment by jchodera** [comment] 2015-12-20 00:29
By the way, it looks like `torsionfit-dev` is not actually being pushed to `anaconda`, since no package is available online.  Seems to be because `devtools/travis-ci/after_success.sh` [isn't found](https://travis-ci.org/choderalab/torsionfit/jobs/97739287#L668-L669):
```
$ source devtools/travis-ci/after_success.sh
/home/travis/build.sh: line 45: devtools/travis-ci/after_success.sh: No such file or directory
```

**Comment by jchodera** [comment] 2015-12-20 00:30
I'm going to perform a couple of direct commits to the `choderalab/torsionfit` repo to get the travis push working.

**Comment by jchodera** [comment] 2015-12-20 00:45
OK, `torsionfit-dev` is being pushed correctly now!

**Comment by jchodera** [comment] 2015-12-20 00:52
I can confirm that installing `torsionfit-dev` on `linux` works just fine.  Closing this for now.

**Closed by jchodera** 2015-12-20 00:52 UTC
